# Generated by Django 3.1 on 2022-04-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numazutourist', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovenuma',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='numazutourist/lovenuma_images', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='numazutourist/place_images', verbose_name='画像'),
        ),
    ]
