# Generated by Django 3.1 on 2022-04-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numazutourist', '0005_auto_20220410_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_sacred',
            field=models.BooleanField(default=False, verbose_name='ラブライブ!聖地'),
        ),
    ]
