# Generated by Django 3.1 on 2022-04-10 07:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='numazutourist/icon_default.png', max_length=255, verbose_name='画像'),
        ),
    ]
